### PR TITLE
Add boilerplate

### PR DESCRIPTION
**Pull request by madig**
This sets up the repository to be easier to work with:

1. Add a generic .gitignore from https://github.com/github/gitignore/blob/master/Python.gitignore
2. Sort imports with isort and format the code with https://github.com/ambv/black
3. Add .editorconfig that tells various editors what settings to use for files
4. Add .pre-commit-config.yaml, a tool that installs other tools that get called on each commit. In this case, the hooks automatically format the code again and look for various paper cuts. Do `pip install pre-commit` to install the main tool and `pre-commit install` in your repository to install the Git hooks. They prolong commit time.
5. Add the tutorial as a sort of smoke test, to see that stuff works.
6. Add setuptools boilerplate for easy package building. Bonus: use the `setuptools_scm` package to automatically version the package according to Git tags. No more bumping the version number, just tag a commit.
7. Add Travis CI integration. This can later be used to automatically deploy a release upon tagging it.

### CODE REVIEW

**Comment by sukop** [comment]
The biggest issue for me with this pull request is the complete reformatting of the codebase. Not only it is not necessary, it completely mangles the code at several places, see `jpeg` or `cff`. Also, "easier to work with": I don't want to install `tox` or `black` just to be able to properly commit anything, and I'm not sure what the `test` tests. I will modify `.gitignore`, though, thanks! Do you wish to commit it separately? And maybe I should create a separate GitHub project for tutorial and documentation...

Please understand, I'm afraid this kind of boilerplate would cause more work, not less, and is not necessary at this early stage of development. If the time comes I wont be able to promptly merge the requests, I will reconsider.

**Comment by madig** [comment]
On the contrary, boilerplate like this is beneficial from the time a project is born to keep it orderly and save you time down the road :) You just need to get used to it.

- Using an automatted formatter(-on-save) frees up brain cycles and ensures that the different opinions about how code should look like are stifled at the core -- very useful in collaborative projects. I personally see no mangling. If you want to keep data blocks compressed, you could use `# fmt: off`/`# fmt: on` blocks though.
- You don't necessarily need to install black, just pre-commit. If you manually want to format and lint stuff, you run `pre-commit run -a` or just commit and add modified files and re-commit.
- tox will help you in testing for both Python 2 and 3 by running tests in both environments.
- If you're interested in having some other tool for project/dependency management, you may want to have a look at https://github.com/takluyver/flit and https://github.com/sdispater/poetry.
- The single test is just a smoke test really, to see that your example keeps working if you refactor the code.
- Why seperate repos? You can generate docs and tutorials with e.g. Sphinx, mkdocs or whatever else and use e.g. GitHub Pages to automatically deploy documentation as you go.

**Comment by sukop** [comment]
I think the boilerplate is a solution to a problem the library does not yet have. Once there are so many contributors and commits the maintainer (me) is not able to keep up with the pace then it would start to make sense to add it, not the other way around.

PS: As an example, the linter completely broke down the formatting of `_z_z` `bytearray` of `jpeg`: the few first spaces are significant as they hint at the missing DC coefficient in the zig-zag sequence and putting each coefficient on a separate line is less readable than it used to be. Repurposing the comments to suppress one particular linter does not seem to me like less work, neither.

**Comment by madig** [comment]
The benefits of a formatter outweight possible inconveniences in the medium and long run.

Regarding tests and CIs, you'll make it harder to maintain and port the library to Python 2+3 if you opt out. It's easy to commit bugs, so a porting effort would require tests for a class and then you do the porting and run those tests with Py2/3 to ensure that stuff keeps working. This PR lays the groundwork for that.

Please add the setup.py at least (or tell me if you want to use poetry or flit instead), you'll just make it harder for contributors because they can't build and install the damn thing.

**Comment by sukop** [comment]
Done in https://github.com/xxyxyz/flat/commit/e1141d6d2f21f6e2915409c41ebc3d197683717d and https://github.com/xxyxyz/flat/commit/977afe6b5a1827faa66626e280fd92caad6e19f0, thanks for the suggestions!

**Comment by madig** [comment]
I recommend you also add the setuptools_scm thing to setup.py -- it will automatically generate a MANIFEST for you and you can stop caring about version numbers, because setup.py will set it automatically according to git tags. No more commit version change and tag, just tag something.

https://github.com/pypa/setuptools_scm

**Comment by sukop** [comment]
I prefer the version number to be explicitly stated in the source code, it's then easier to find it out as it wont require running the script.

What Python 2+3 goes, I plan to drop the support for version 2 once the Python 3 work is ready.

**Pull request closed without merging**
