### PR TITLE
Adding tracking to text.

### PR DESCRIPTION
**Pull request by michielkauwatjoe**
Hi, we've added text tracking, could you review the changes?

### CODE REVIEW

**Comment by sukop** [comment]
Thank you! I'm still trying to wrap my head around it, but I can already offer a few comments:

- Just to confirm we are in agreement on terminology, by "tracking" you mean the displacement added to each glyph, in addition to horizontal advance and kerning (`Tc` operator in PDF terms), correct? What does tracking of 1000 mean in you patch? Take for example `width` method, which returns scaled (or "real") value, why does it just add `tracing` to it, regardless of size?

- Any additional functionality should also work in SVG (if applicable). That means employing the `dx` attribute of `tspan`. Very first commit of Flat used to include `dx`, you can compare it there, for example.

- It seems to me that `rasterize` is definitely not correct as it should apply the tracking to each character, not just at the very end of each "run". Similarly in `boundaries` I don't think it is correct to add tracking of whole `string` to both `word` and `space`.

- In `strike` class, I would prefer to have a separate method for setting the tracking, as opposed to set in in `size`. That way you don't have to repeat `size` when you want to set `tracking`, and vice versa.

**Comment by michielkauwatjoe** [comment]
@sukop Hi, thank you for your quick response! I'll pass your comments on to @petrvanblokland, since these are his changes and he's more knowledgeable about the principles of type.

**Comment by michielkauwatjoe** [comment]
@sukop Petr is in some meetings today, so I'm passing on his replies to your comments below. We've also made some changes to `rasterize` and `strike` like you asked, could you have a look?

Petr (@petrvanblokland):

> - Just to confirm we are in agreement on terminology, by "tracking" you mean the displacement added to each glyph, in addition to horizontal advance and kerning (Tc operator in PDF terms), correct? What does tracking of 1000 mean in you patch? Take for example widthmethod, which returns scaled (or "real") value, why does it just add tracing to it, regardless of size?

That indeed is tracking.
There are three values that define the position of the next glyph in typography.
- width of the glyph
- tracking (value added to every glyph width, also called letter-spacing)
- kerning (value defined inside the font, depending on glyph-glyph or glyph-group or group-glyph or group-group combination. In that order, glyph-glyph kerning overwrite the kerning of groups that they glyphs are in. 

Kerning is always defined in units of the font-em size (font.unitsPerEm). If the em square inside the font is 1000 (most often for OTF) then kerning units are 1/1000 em. But some (older) TTF fonts have 2048, and there are reasons to make screen fonts having an em of 512 or even less, then the kerning is in those units.

Then there is the question of the unit value of the tracking to choose.
Historically there have been differences. In old-days Quark Express a units of tracking was 1/200 of the width of the zero, which is a very random kind of choice. Fortunately that is not around anymore. In Adobe-land a tracking units is expressed in 1/1000 of the em. 
But in CSS is it a percentage of the em, so 1/100 of an em. 
The tendency is to adapt to the measurements of CSS, so in that case the unit would be 1/100 em.

We could decide either way, as long as consistent and documented.

>  - Any additional functionality should also work in SVG (if applicable). That means employing the dx attribute of tspan. Very first commit of Flat used to include dx, you can compare it there, for example.

Indeed it would be best to have SVG as compatible as possible. But in general, do have tracking available in PDF is essential for the quality of the typography. One of the functions of tracking is to add width to small font sizes for reading, in case the font does not have an optical size axis (as in some Variable Fonts) or not a text equivalent next to a display version of the font. In small size controlling the contrast of the letters – not making thin parts too thin – and the spacing is really important. 

> -  It seems to me that rasterize is definitely not correct as it should apply the tracking to each character, not just at the very end of each "run". Similarly in boundaries I don't think it is correct to add tracking of whole string to both word and space.

Maybe not. It needs for better understanding wat the difference is what these are doing.
The reason to multiply at the end is efficiency, adding one multiplication instead of adding inside the loop. But that can be different of course.
In the placement of the characters, indeed, the addition needs to be part of every x-advance inside the loop.

> -  In strike class, I would prefer to have a separate method for setting the tracking, as opposed to set in in size. That way you don't have to repeat size when you want to set tracking, and vice versa.

strike.tracking = value would work too.

**Comment by michielkauwatjoe** [comment]
Closing this for now, setting tracking doesn't give the desired results yet. I'll reopen it when it's fixed.

**Pull request closed without merging**
